services:
  - type: web
    name: visionbot
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5